name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: diberry-expressjs-deploy-with-github-action   # set this to your Azure web app name
  AZURE_WEBAPP_PACKAGE_PATH: 'packages/react-client-app-1/build'      # set this to the path to your web app project, defaults to the repository root

  NODE_VERSION: '16.0'                # set this to the node version to use    
    
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies - with npm workspaces
        run: npm install
      - name: Build React client
        run: npm run build --if-present
      - name: remote-bash
        uses: shinhwagk/remote-bash@0.0.1
        with:
          args: arg1 arg2
        env:
          REMOTE_BASH_URL: https://raw.githubusercontent.com/diberry/npm-workshape-github-action-test-1/main/recursive-dir-listing.sh
      - name: 'Deploy to Azure WebApp ${{ env.AZURE_WEBAPP_NAME }} at path $${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}        